version: '3.4'

services:
  backend-node:
    container_name: backend-node
    build: .
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
     - .env
    command: /bin/sh -c "while sleep 1000; do :; done;"
    networks:
      - network1
networks:
  network1:
    name: mi_red
    external: true
  # db:
  #   image: mongo
  #   ports:
  #     - 27017:27017